CREATE TABLE promotion (
 id SERIAL NOT NULL,
 amount INT NOT NULL,
 price DECIMAL(18,2) NOT NULL,
 PRIMARY KEY (id)
);

CREATE TABLE product (
 id SERIAL NOT NULL,
 name  VARCHAR(1) NOT NULL,
 price DECIMAL(18,2) NOT NULL,
 promotion_id SERIAL NOT NULL,
 PRIMARY KEY (id),
 FOREIGN KEY (promotion_id) REFERENCES promotion (id)
 ON DELETE CASCADE
);